live_config_reload = true
# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
foreground = "#e0def4"
background = "#191724"
dim_foreground = "#908caa"
bright_foreground = "#e0def4"

[colors.cursor]
text = "#e0def4"
cursor = "#524f67"

[colors.vi_mode_cursor]
text = "#e0def4"
cursor = "#524f67"

[colors.search.matches]
foreground = "#908caa"
background = "#26233a"

[colors.search.focused_match]
foreground = "#191724"
background = "#ebbcba"

[colors.hints.start]
foreground = "#908caa"
background = "#1f1d2e"

[colors.hints.end]
foreground = "#6e6a86"
background = "#1f1d2e"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#e0def4"
background = "#1f1d2e"

[colors.selection]
text = "#e0def4"
background = "#403d52"

[colors.normal]
black = "#26233a"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

[colors.bright]
black = "#6e6a86"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

[colors.dim]
black = "#6e6a86"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"


[window]
  option_as_alt = 'Both'
  decorations = 'None'
  startup_mode = 'SimpleFullscreen'

[font]
  size = 14.0
  offset.y = 2

[font.bold]
  family = "JetBrainsMono Nerd Font Propo"
  style = "Regular"

[font.bold_italic]
  family = "JetBrainsMono Nerd Font Propo"
  style = "Regular Italic"

[font.italic]
  family = "JetBrainsMono Nerd Font Propo"
  style = "Light Italic"

[font.normal]
  family = "JetBrainsMono Nerd Font Propo"
  style = "Light"

[keyboard]
bindings = [ 
  { key = 'U', mods = "Command", command = { program = "/opt/homebrew/bin/alacritty", args = ["msg", "config", "window.opacity=0.8"] } },
  { key = 'U', mods = "Command|Shift", command = { program = "/opt/homebrew/bin/alacritty", args = ["msg", "config", "window.opacity=1"] } },
]

[bell]
command = { program = "osascript", args = ["-e", "beep"] }
