[window]
  option_as_alt = 'Both'
  decorations = 'None'
  opacity = 0.96
  startup_mode = 'SimpleFullscreen'

[font]
  size = 14.0

[font.bold]
  family = "JetBrainsMono Nerd Font Mono"
  style = "Regular"

[font.bold_italic]
  family = "JetBrainsMono Nerd Font Mono"
  style = "Bold Italic"

[font.italic]
  family = "JetBrainsMono Nerd Font Mono"
  style = "Light Italic"

[font.normal]
  family = "JetBrainsMono Nerd Font Mono"
  style = "Light"

[colors.primary]
  background = "#16161e"


