tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "fzf"
brew "node"
brew "python@3.9"
brew "the_silver_searcher"
brew "tmux", args: ["HEAD"]
brew "zsh"
brew "reattach-to-user-namespace"
brew "wget"
cask "1password"
cask "firefox"
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "font-cascadia-code"
cask "google-chrome"
cask "sizeup"
cask "iterm2"
cask "plex-media-server"
# Does not work on M1, installed manually with rozetta
# brew "neovim", args: ["HEAD"]
# brew "git"
